# Generated by Django 2.0.7 on 2018-08-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=99999)),
                ('agree_vote', models.IntegerField(default=0)),
                ('disagree_vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_ID', models.IntegerField(default=0)),
                ('movie_published', models.DateTimeField(verbose_name='movie published')),
            ],
        ),
        migrations.AddField(
            model_name='movie_comments',
            name='movie_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie_Info'),
        ),
    ]
