# Generated by Django 2.0.7 on 2018-08-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_info',
            name='movie_published',
        ),
    ]
